FROM node:lts-alpine

COPY package.json .
RUN apk add --no-cache make gcc g++ python3 && \
  npm install && \
  npm rebuild bcrypt --build-from-source && \
  apk del make gcc g++ python3

RUN npm install -g nodemon

WORKDIR /api

EXPOSE 8081